### ISSUE TITLE
Please add support for dump_game_options configuration

### ISSUE THREAD

**Issue by hulovexu1314** [LittleZen/Cyberpunk2077-Patch-Easy-Installer#15]
dump_game_options: Will dump all options and their default values in the log file (default: false)

**Comment by LittleZen** [comment]
Hi @hulovexu1314, i am not sure to understand what do you mean. Are you talking about "set default" option, for restore the settings to the default values ?

**Comment by hulovexu1314** [comment]
@LittleZen Look here https://github.com/yamashi/PerformanceOverhaulCyberpunk/wiki  Last configuration item. I went to bed too late……

**Comment by LittleZen** [comment]
I miss that, with the last release! 
Thanks for letting me know, it will be released with the next release!

#Accepted

**Comment by LittleZen** [comment]
Added with version 2.6

#Close
