### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by snookilow** [LittleZen/Cyberpunk2077-Patch-Easy-Installer#18]
Doesn't work on win7 :( 
Writes missing library metroframework.dll
If you fix it I will be glad :)

**Comment by snookilow** [comment]
but now everything worked, maybe I did something wrong

**Comment by LittleZen** [comment]
That's great ! So have you fixed it ?

**Comment by snookilow** [comment]
> 
> 
> That's great ! So have you fixed it ?

Yes. It's okay, I was careless when unpacking the archive :)

**Comment by LittleZen** [comment]
Yep, you should decompress the entire archive, cause it was linked to metroframework dlls!

Glad it works, and be sure to checkout the new version!

**Comment by snookilow** [comment]
> 
> 
> Yep, you should decompress the entire archive, cause it was linked to metroframework dlls!
> 
> Glad it works, and be sure to checkout the new version!

Yep, thx mate)
