### ISSUE TITLE
Critical Error! Screen

### ISSUE THREAD

**Issue by illumiajavier** [LittleZen/Cyberpunk2077-Patch-Easy-Installer#19]
Extracted and launched executable - It autodetects the correct Steam path for my game, then gives error code 1 with no further details.
![Screenshot 2020-12-20 081038](https://user-images.githubusercontent.com/28305344/102714178-e63baf00-429a-11eb-9ac1-2728b0dc52a8.jpg)

**Comment by LittleZen** [comment]
After this error, can you click on "Check For Patch Updates" button? Does it works?

**Comment by illumiajavier** [comment]
Gives the same error after clicking the Check For Patch Updates. It seems to think the patch is already installed after relaunching the program. No blocks from AV software noted, either. Same error appears when clicking anything in the re-launched instance.

[cid:image001.png@01D6D6A8.6EBCE010]



Javier Santana
Senior Systems Engineer at ePlus Technology, inc.
O: 703.984.8353 | M: 808.754.3392 | [http://s.c.lnkd.licdn.com/scds/common/u/img/webpromo/btn_in_20x15.png] View My LinkedIn<http://www.linkedin.com/in/javierasantana>

**Comment by LittleZen** [comment]
I will investigate on it. Thank you for the report! Seems strange ... are you running it as admin? Have you tried to manually select the game folder ?

**Comment by illumiajavier** [comment]
Yep, tried running as admin, and tried manually pointing to the drive with steamlibrary/common, Cyberpunk, etc. This isn’t related to the console being patched out in 1.05, you think?



Javier Santana
Senior Systems Engineer at ePlus Technology, inc.
O: 703.984.8353 | M: 808.754.3392 | [http://s.c.lnkd.licdn.com/scds/common/u/img/webpromo/btn_in_20x15.png] View My LinkedIn<http://www.linkedin.com/in/javierasantana>

**Comment by LittleZen** [comment]
That strange ... i didn't met those error, and i'm trying to replicate it without success ... anyway the error shown is not directly linked to the patch, but they are installation error ...  (in the tool's folder you should be able to see "game_path" file, delete it)

**Comment by LittleZen** [comment]
Hmm ... was looking deep on this bug and i read:

 *"...tried manually pointing to the drive with steamlibrary/common, Cyberpunk, etc."* 

... what do you mean with "etc" ... you have to point the main directory of Cyberpunk2077 not the x64 folder, are you aware about that?

**Comment by illumiajavier** [comment]
Yeah, “etc.” as in I pointed to the full Cyberpunk directory and didn’t want to type the entire thing out. In my case, that’s “D:\SteamLibrary\steamapps\common\Cyberpunk 2077”.



Javier Santana
Senior Systems Engineer at ePlus Technology, inc.
O: 703.984.8353 | M: 808.754.3392 | [http://s.c.lnkd.licdn.com/scds/common/u/img/webpromo/btn_in_20x15.png] View My LinkedIn<http://www.linkedin.com/in/javierasantana>

**Comment by LittleZen** [comment]
Unfortunatly i don't have a steam version for debug it ... anyway i will attach more debug information with the next release of the patcher ... hope it could help you ... i also suggest to check the main patch from yamashi and go ahead with manual installation :(

**Comment by LittleZen** [comment]
@illumiajavier 

new version 2.8 is out, i've integrated new messagebox that should help us detect the bug. Keep me informed if you have new results

**Comment by StKob** [comment]
@LittleZen You probably introduced bugs in 2.9 cause I'm getting critical error after clicking automatic path discovery. Manual also didnt work. Looks like problem lies in installing process. I reverted back to 2.8 and It's working correctly.

**Comment by LittleZen** [comment]
Can you provide more details about the bug? Which is the error ?

**Comment by LittleZen** [comment]
@StKob @illumiajavier 

Bug found, working on it! 


Thank you for the report, and i'm sorry !

**Comment by LittleZen** [comment]
@StKob @illumiajavier 


New version 3.0 released, keep me informed if that work!

**Comment by Saibamen** [comment]
@LittleZen: I think it is right time to implement your own Logger class and save logs in file (log every `try catch`, log INFO to see that happend before exception etc)

**Comment by LittleZen** [comment]
I've already created a log file for some other application that i've developed. Cause it is just a simple installer i don't think is useful create a log file ... i think it will just be a unecessary workload. If there is some kind of error it should be directly pop-up as messagebox. Every button should do just 1/2 taks, so that's why i didn't implement it

`outputFile.Write(DateTime.Now.ToString("[yyyy/MM/dd hh:mm:ss]: \n <MylogMessageToLogFile>"));`

**Comment by LittleZen** [comment]
Anyway i reworked all messagebox since version 2.7 shown here ... that should help us to detect the problem

**Comment by Saibamen** [comment]
@illumiajavier: Please check latest master branch and send new screenshot with Exception

**Comment by illumiajavier** [comment]
Sorry for the late update - Downloaded 3.0, automatically found game path with no problems, and applied the default settings (plus disabling antialiasing). Game launches okay afterwards and console is present. Definitely noticing a performance boost as well. Good to close this out.
