### ISSUE TITLE
please update! Support more configurations!

### ISSUE THREAD

**Issue by hulovexu1314** [LittleZen/Cyberpunk2077-Patch-Easy-Installer#20]
The latest version adds:

Disable_boundary_teleport
Disable_intro_movies
Disable_vignette

Option configuration
Update support!

**Comment by LittleZen** [comment]
Working on it ...

**Comment by LittleZen** [comment]
I've downloaded the lastest release of yamashi's patch, and i didn't found those features ... can you provide more details ?

**Comment by hulovexu1314** [comment]
@LittleZen Download the latest patch to run the game will be generated in config.json Within the document

**Comment by LittleZen** [comment]
![image](https://user-images.githubusercontent.com/35767830/102714608-1c475600-42d0-11eb-8f31-e1ca8bc1d7c8.png)

i've downloaded now the last update from yamashi, and still not found those features (even in the readme/wiki they are not included...?)

**Comment by hulovexu1314** [comment]
"disable_boundary_teleport":false
Disable_intro_movies…
Disable_vignette…

**Comment by hulovexu1314** [comment]
> ![image](https://user-images.githubusercontent.com/35767830/102714608-1c475600-42d0-11eb-8f31-e1ca8bc1d7c8.png)
> 
> i've downloaded now the last update from yamashi, and still not found those features (even in the readme/wiki they are not included...?)

runing game !!Running the game will generate it

**Comment by LittleZen** [comment]
I'm currently downloading the patch 1.05 (so, i can not check it now), those features will be added soon!

thank you for the report, i will leave this issues open until the next release! 

(if you could share a screenshot of config.json file, i can start working on it now!)

**Comment by hulovexu1314** [comment]
@LittleZen 
{
    "avx": true,
    "console": true,
    "console_key": 192,
    "cpu_memory_pool_fraction": 0.5,
    "disable_antialiasing": false,
    "disable_async_compute": false,
    "disable_boundary_teleport": true,
    "disable_intro_movies": true,
    "disable_vignette": true,
    "dump_game_options": false,
    "enable_debug": false,
    "gpu_memory_pool_fraction": 1.0,
    "memory_pool": true,
    "remove_pedestrians": false,
    "skip_start_menu": true,
    "smt": true,
    "spectre": true,
    "virtual_input": true
}
![2020-12-20 214255](https://user-images.githubusercontent.com/22097752/102714866-97c6f880-430c-11eb-8953-6b09a67aab32.png)

**Comment by hulovexu1314** [comment]
> I'm currently downloading the patch 1.05 (so, i can not check it now), those features will be added soon!
> 
> thank you for the report, i will leave this issues open until the next release!
> 
> (if you could share a screenshot of config.json file, i can start working on it now!)

Thank you for your work! !

**Comment by LittleZen** [comment]
@hulovexu1314 does those settings are the default one, or you have changed something ?

**Comment by hulovexu1314** [comment]
> @hulovexu1314 does those settings are the default one, or you have changed something ?

 "disable_intro_movies": true,
 "disable_vignette": false,
 "disable_boundary_teleport": false
From the latest version 1.3.0 default

**Comment by LittleZen** [comment]
What about "consoleKey" value ? 192 is the default ?

**Comment by hulovexu1314** [comment]
yes

> What about "consoleKey" value ? 192 is the default ?

yes default key

**Comment by LittleZen** [comment]
@hulovexu1314 

New version 2.8 is out. I'm working for release a customizable version of ConsoleKey, but all new features should be included. Let me know if that works, and stay tunned for the release 2.9 !

**Comment by LittleZen** [comment]
Released version 2.9, now you can customize the ConsoleKey

#Closed
