### ISSUE TITLE
Uninstall action not deletes all files

### ISSUE THREAD

**Issue by Saibamen** [LittleZen/Cyberpunk2077-Patch-Easy-Installer#25]
2 files still exists:

![obraz](https://user-images.githubusercontent.com/905878/102727903-a7e8d300-4320-11eb-9c96-4749e3d379fc.png)

**Comment by LittleZen** [comment]
Thanks for the report, i will fix it with the next release!

**Comment by Saibamen** [comment]
Don't close issues if fix was not already done...

**Comment by LittleZen** [comment]
i've already commit it... just need to release the version 3.1 i will do it tomorrow
