### ISSUE TITLE
Automatic detecting path ignores selected settings

### ISSUE THREAD

**Issue by Saibamen** [LittleZen/Cyberpunk2077-Patch-Easy-Installer#26]
Steps:

1. Click `Uninstall`
2. Uncheck some/all checkboxes in Settings section
3. Click `Automatic Detect GOG/Steam Path`

Current:
![obraz](https://user-images.githubusercontent.com/905878/102728098-bf748b80-4321-11eb-8d34-5665e0904b36.png)

Expected:
![obraz](https://user-images.githubusercontent.com/905878/102728285-e2ec0600-4322-11eb-8d3d-2646451380b3.png)

**Comment by LittleZen** [comment]
We should reload the settings after the reinstallation! Thank you, i will check it !

**Comment by Saibamen** [comment]
This bug also exists for first installation, so we should read current settings at every installation

**Comment by LittleZen** [comment]
Already exist a method called `LoadSettings(generalPath);` i've tried to add it at the end of the detection, but it fail and generate an exception ... i'm working on it, have you any idea ? 🤔

**Comment by Saibamen** [comment]
What exception?

You can't use `LoadSettings()` here, because it doesn't change anything.

Export JSON saving code into separate function and use it in `PatchGame()`

**Comment by LittleZen** [comment]
Hey @Saibamen !

I was working on this fix and i thought that could be an easy method for fix this issues: is stupid left the groupbox enabled when the patch is not installed, so i set all groupbox on disabled and i will call a function that will enable it only if the patch is installed (once you install the patch, the groupbox will be enabled with the default value, and when you unistall the patch, the groupbox will be disabled)

That's how the Patcher looks like when you don't have installed the patch:
![image](https://user-images.githubusercontent.com/35767830/102765566-122f6100-437d-11eb-8616-c3a3849c0253.png)

After one of the installation method (without any customization, the checkbox will be setted to the default values, according to yamashi patch):

![image](https://user-images.githubusercontent.com/35767830/102766036-d052ea80-437d-11eb-9d21-728d1e9bb505.png)


I just don't understand why i can not refer to the group box meanwhile i'm in this function ... seems like i can not reach out any object ...

![image](https://user-images.githubusercontent.com/35767830/102764913-30e12800-437c-11eb-9f7b-ae218d91c33a.png)

P.s. I will tag @JayVee732 cause i see that he's expert, and maybe could help us to find a path to follow!

**Comment by LittleZen** [comment]
I've worked in the new commits, and i've started to looking for a fix ... i will waiting a little bit more before the next release!

**Comment by LittleZen** [comment]
#Closed

Fixed with version 3.1
