### ISSUE TITLE
Please commence a DMCA removal for the malware infected upload on modscyberpunk2077.com

### ISSUE THREAD

**Issue by Squall-Leonhart** [LittleZen/Cyberpunk2077-Patch-Easy-Installer#28]
The site above has hosted a miner malware infected binary of 2.7 at hxxps://www.modscyberpunk2077.com/cyberpunk-2077-easy-patcher/

https://www.virustotal.com/gui/file/a45176dbc2553cb0f6835239e139f09eadc8bfe057436f7e1342683cfec68020/detection

![image](https://user-images.githubusercontent.com/1098176/102732719-9094fe80-438f-11eb-92ba-03264f8961c2.png)

**Comment by LittleZen** [comment]
Hey @Squall-Leonhart, thank you for the report!

i've submitted a report at the host  ... hope they will remove it soon...

**Comment by LittleZen** [comment]
Hey @Squall-Leonhart,

Just for keep you informed, it seems to be removed, thank you man !
