### ISSUE TITLE
Differences in config.json

### ISSUE THREAD

**Issue by Saibamen** [LittleZen/Cyberpunk2077-Patch-Easy-Installer#43]
EasyPatcher have old settings.

Please read official documentation: https://wiki.cybermods.net/cyber-engine-tweaks/getting-started/configuration

![obraz](https://user-images.githubusercontent.com/905878/109399500-1195e680-793b-11eb-811c-d3dc85f8909a.png)

**Comment by Saibamen** [comment]
But I have question - do we still need to have these options in EasyPatcher?

From documentation:

The config file is automatically generated. It **is not recommended** that you edit it manually. Please **use the Settings tab** in the CET overlay to change the configurations.

**Settings tab documentation**: https://wiki.cybermods.net/cyber-engine-tweaks/console/usage#settings

**Comment by LittleZen** [comment]
Guess we can consider EasyPatcher as outdated! 

I've supported yamashi json config file for a while, but seems EasyPatcher is no longer needed since yamashi released the in-game menu ... i'm thinking about continue this project, or just simple close it :( 

Anyway, thank you for the support <3

**Comment by LittleZen** [comment]
Closed due to outdated :/
