### ISSUE TITLE
Thank you very much. Can I share this tool?

### ISSUE THREAD

**Issue by hulovexu1314** [LittleZen/Cyberpunk2077-Patch-Easy-Installer#7]
First of all thank you very much! This game optimization is really bad!
After the tool is updated, I want to share this awesome tool on the 3DM forum. Can I?
Thank for LittleZen!  yamashi!

**Comment by hulovexu1314** [comment]
Can you add an input box to customize the memory pool (CPU memory) (GPU memory )?

**Comment by LittleZen** [comment]
@hulovexu1314 accepted, 
it will released within next version. Feel free to share, but remember to attach the credits!

**Comment by hulovexu1314** [comment]
@LittleZen Thank you very much!

**Comment by LittleZen** [comment]
I'm working on memory pool, it will be released soon (with new stuff), in the meanwhile, can you please share here the link to the 3DM forum post

**Comment by hulovexu1314** [comment]
@LittleZen Okay thank you! 3DM Forum Sharing Link: https://bbs.3dmgame.com/thread-6110790-1-1.html，
Of course I want to put the two tools in one post for your convenience. Hahaha, of course I can also post two posts.
Finally, I would like to localize your tools, because many of us here don’t understand English very much, so I don’t know if you can agree.

**Comment by LittleZen** [comment]
@hulovexu1314 is not a problem the translation, if you want do it, just do it, the code is open source for anyone (check out the latest version 2.2!) !

(Last thing: your link to 3dmgame seems to be broken!)

**Comment by hulovexu1314** [comment]
@LittleZen Sorry, the link has an extra comma. . . Now the link should be opened normally. Thank you!

**Comment by LittleZen** [comment]
Yes, i just released the version 2.2 right now ! Check out the new features, and enjoy it ! 

Link: https://github.com/LittleZen/Cyberpunk2077-Patch-Easy-Installer/releases

**Comment by hulovexu1314** [comment]
@LittleZen Thank you so much for sharing! Thank you! 3DM Share Link： https://bbs.3dmgame.com/thread-6110790-1-1.html

**Comment by LittleZen** [comment]
😉 Closed !
