### ISSUE TITLE
Cannot open the game after saving the configuration!

### ISSUE THREAD

**Issue by hulovexu1314** [LittleZen/Cyberpunk2077-Patch-Easy-Installer#9]
@LittleZen After saving the configuration, the tool should add "cpu_memory_pool_fraction" and "gpu_memory_pool_fraction" in the config.json file
The value is set to an integer instead of a string
Otherwise, the game cannot be played normally, hope to fix it soon!
"cpu_memory_pool_fraction": "1" error!!!
"cpu_memory_pool_fraction": 1   yes!!!

**Comment by JayVee732** [comment]
Hi there,

I've fixed this issue in #8, I just need it to be reviewed and committed to the master branch.

Thanks!

**Comment by LittleZen** [comment]
Yes, my fault, i 'm working on #8 for fix it. I will release v2.3 soon !

**Comment by LittleZen** [comment]
Fixed, thanks to @JayVee732, version 2.3 as been released with fix. Keep me informed if it works! (i will not close this issue until that)
